[package]
name = "tower-sessions"
description = "🥠 Cookie-based sessions as a `tower` middleware."
version = "0.0.0"
edition = "2021"
license = "MIT"

[features]
default = ["axum-core", "memory-store"]
memory-store = []
redis-store = ["fred"]
sqlx-store = ["sqlx"]
sqlite-store = ["sqlx/sqlite", "sqlx-store"]
postgres-store = ["sqlx/postgres", "sqlx-store"]
tokio = ["dep:tokio"]

[dependencies]
async-trait = "0.1"
http = "0.2"
parking_lot = { version = "0.12", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
time = { version = "0.3", features = ["serde"] }
tower-cookies = "0.9"
tower-layer = "0.3"
tower-service = "0.3"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
axum-core = { optional = true, version = "0.3" }
fred = { optional = true, version = "6", features = ["serde-json"] }
sqlx = { optional = true, version = "0.7.1", features = [
    "time",
    "uuid",
    "runtime-tokio",
] }
tokio = { optional = true, version = "1", features = ["full"] }

[dev-dependencies]
axum = "0.6"
hyper = "0.14"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tokio-test = "0.4"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "counter"
required-features = ["axum-core", "memory-store"]

[[example]]
name = "counter-extractor"
required-features = ["axum-core", "memory-store"]

[[example]]
name = "redis-store"
required-features = ["axum-core", "redis-store"]

[[example]]
name = "sqlite-store"
required-features = ["axum-core", "sqlite-store", "tokio"]

[[example]]
name = "postgres-store"
required-features = ["axum-core", "postgres-store", "tokio"]
